spring:
  application:
    name: ai-test
  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: ${GEMINI_AI_SECRET_KEY}
        chat:
          options:
            model: gemini-2.5-flash
logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen3.5:latest
#    openai:
#      api-key: {$OPEN_AI_SECRET_KEY}
#      chat:
#        options:
#          model: gpt-4o-mini
#          temperature: 0.9
